name: Build and Publish Docker Image

on:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          REPO_NAME=${{ github.repository }}
          # Convert repository name to lowercase
          REPO_NAME=${REPO_NAME,,}
          if [ "${{ github.event_name }}" == "release" ]; then
            IMAGE_TAG=ghcr.io/${REPO_NAME}:latest
            docker buildx build --push --cache-from=type=gha --cache-to=type=gha,mode=max -t $IMAGE_TAG .
          else
            docker buildx build --cache-from=type=gha --cache-to=type=gha,mode=max -t $REPO_NAME .
          fi

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io
